"""empty message

Revision ID: 4acaa2942512
Revises: 
Create Date: 2024-01-14 23:48:53.019288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acaa2942512'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MarketplaceUser',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('City',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['Country.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Buyer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('marketplace_user_id', sa.BigInteger(), nullable=True),
    sa.Column('billing_city_id', sa.BigInteger(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['billing_city_id'], ['City.id'], ),
    sa.ForeignKeyConstraint(['marketplace_user_id'], ['MarketplaceUser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ItemCategory',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Category.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['Item.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'category_id')
    )
    op.create_table('SalesOrder',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('shipping_country_id', sa.BigInteger(), nullable=True),
    sa.Column('shipping_city_id', sa.BigInteger(), nullable=True),
    sa.Column('marketplace_id', sa.BigInteger(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['Buyer.id'], ),
    sa.ForeignKeyConstraint(['marketplace_id'], ['Marketplace.id'], ),
    sa.ForeignKeyConstraint(['shipping_city_id'], ['City.id'], ),
    sa.ForeignKeyConstraint(['shipping_country_id'], ['Country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ItemOrdered',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['Item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['SalesOrder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('item_type')

    op.drop_table('ItemOrdered')
    op.drop_table('SalesOrder')
    op.drop_table('ItemCategory')
    op.drop_table('Buyer')
    op.drop_table('City')
    op.drop_table('MarketplaceUser')
    # ### end Alembic commands ###
